// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6V8vPU81LaHxYn7bEtqcGnGlAcQRpUlk',
    appId: '1:116072978940:web:79d074d838c489d8587a79',
    messagingSenderId: '116072978940',
    projectId: 'testbase-cf69f',
    authDomain: 'testbase-cf69f.firebaseapp.com',
    storageBucket: 'testbase-cf69f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdE5dc1V6Nm6KlfmOQoZQsD0vwnQ6eWY',
    appId: '1:116072978940:android:b9382da0c20f691d587a79',
    messagingSenderId: '116072978940',
    projectId: 'testbase-cf69f',
    storageBucket: 'testbase-cf69f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHyIEw0K1hcpSenYk9YrkjW9yIINmHYCA',
    appId: '1:116072978940:ios:0fc959b59eb5a36b587a79',
    messagingSenderId: '116072978940',
    projectId: 'testbase-cf69f',
    storageBucket: 'testbase-cf69f.appspot.com',
    iosClientId: '116072978940-t4kcr9js4kign2dp5n469fngg1vr6m2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHyIEw0K1hcpSenYk9YrkjW9yIINmHYCA',
    appId: '1:116072978940:ios:0fc959b59eb5a36b587a79',
    messagingSenderId: '116072978940',
    projectId: 'testbase-cf69f',
    storageBucket: 'testbase-cf69f.appspot.com',
    iosClientId: '116072978940-t4kcr9js4kign2dp5n469fngg1vr6m2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
